### PR TITLE
More convenience

### PR DESCRIPTION
**Pull request by BeastyBlacksmith**
I found these methods useful when creating my first Graphic with Luxor

### CODE REVIEW

**Comment by cormullion** [comment]
Hi, that’s great! Thanks for doing this. I hope the package meets your needs...

Is there an overlap in functionality between `isinside(pt, bbox)` and `in(pt, bbox)`? I think your name is probably better; I’m OK to synonym one to the other if they’re the same.

**Comment by BeastyBlacksmith** [comment]
you are right, I didn't discover `isinside`. And I was not sure, how the points of the BoundingBox are ordered. So we change the definition to
```julia
Base.in(pt,bbox) = isinside(pt,bbox)
```

**Comment by cormullion** [comment]
Sounds good. As long as the tests pass on Linux and Windows it will be OK, Cairo being broken on macOS... :(

**Comment by BeastyBlacksmith** [comment]
done, now that the ordering is guaranteed, I also changed the `rand` function to not use UnitStepRanges.

**Comment by cormullion** [comment]
Thanks for this!

**Comment by cormullion** [comment]
Some time if you’ve got a spare moment could you check the current (master) version of `rand(bb)`? I found some problems when testing it on edge cases and tried to fix them. I don’t want to break your code....😢

**Comment by BeastyBlacksmith** [comment]
that's definitely the correct version. It is still slightly skewed in that you can reach the lower bounds for `x` and `y`, but not the upper bounds ( so it is not strictly _inside_ ).
Does not matter for my use-cases, but good to have in mind.

**Comment by cormullion** [comment]
Thanks! Probably some `<`/`<=` thing going on... I'll worry about it one day when I can't think of anything else to do...

**Comment by BeastyBlacksmith** [comment]
Its just because `rand` can give `0` but not `1`.

**Pull request merged**
