### PR TITLE
Added Towards to Turtle

### PR DESCRIPTION
**Pull request by osoleve**
Added turtle's Towards function, that updates the turtle's orientation to face a given point.

### CODE REVIEW

**Comment by cormullion** [comment]
Hi, that's a good idea! Thanks. Perhaps add a call to test/turtle-test.jl?

**Comment by osoleve** [comment]
> Hi, that's a good idea! Thanks. Perhaps add a call to test/turtle-test.jl?

Will do after work today 👍

**Comment by osoleve** [comment]
A side effect of the test I added is that Raphael's name is now red. This wasn't intentional but it felt right so I left it.

**Comment by cormullion** [comment]
Thanks! Testing at the moment is mostly "does it run without errors"... 😂

**Pull request merged**
