### PR TITLE
Update around broadcasting

### PR DESCRIPTION
**Pull request by hyrodium**
Sorry for the late PR.
This PR is related to this comment: https://github.com/JuliaGraphics/Luxor.jl/pull/295#issuecomment-1983474107.

Changes in this PR:

- `Point(1,2) .+ 3` is now invalid.
	- Use `Point(1,2) + Point(3,3)` instead.
	- `CHANGELOG.md` is also updated.
- `[Point(1,2), Point(4,1)] .+ Point(3,4)` is now valid.
	- This change is profitable for reducing `Ref` in code.
		- i.e. we don't need `Ref` in `between.(Ref(pt1), Ref(pt2), range)`.
		- I have also removed `between` methods introduced in https://github.com/JuliaGraphics/Luxor.jl/commit/90d006b539c611008d4a6112e9d7e3b752186788.
	- Historical note
		- On the latest release [`v3.8.0`](https://github.com/JuliaGraphics/Luxor.jl/releases/tag/v3.8.0), `[Point(1,2), Point(4,1)] .+ Point(3,4)` was valid too.
		- After [PR#294](https://github.com/JuliaGraphics/Luxor.jl/pull/294), `[Point(1,2), Point(4,1)] .+ Point(3,4)` turned invalid, and we needed to write `[Point(1,2), Point(4,1)] .+ Ref(Point(3,4))` instead.
		- This PR reverts the broadcasting behavior, and `[Point(1,2), Point(4,1)] + Point(3,4)` is now valid.
		- Of course, `[Point(1,2), Point(4,1)] .+ Ref(Point(3,4))` is also still valid.

### CODE REVIEW

**Comment by cormullion** [comment]
How’s this going?

**Comment by hyrodium** [comment]
I'm sorry that I did not have time for OSS in recent days. I will try updating this PR tomorrow! 💪

**Comment by hyrodium** [comment]
I think the dictionary order with `Point` should be also removed before releasing v4.

```julia
julia> Point(1,3) < Point(0,4)
false

julia> Point(1,3) < Point(2,1)
true
```

If you agree with that, I will fix this in another PR!

x-ref: https://github.com/JuliaGraphics/Luxor.jl/blob/master/test/point-arithmetic.jl#L46-L48

**Comment by cormullion** [comment]
Sure! Just let me know when you’ve finished all the changes you feel are important by- then I can go ahead and make the 4.0 release.

**Comment by hyrodium** [comment]
This is ready for review!

**Pull request merged**
