### PR TITLE
Alpha settings in placeimage()

### PR DESCRIPTION
**Pull request by Sov-trotter**
The `placeimage` function for image matrix can use some alpha settings similar to the ones for png/svg.

### CODE REVIEW

**Comment by cormullion** [comment]
Looks cool! You'll probably need to update docstrings and docs, and perhaps add tests - since this stuff is (I think) used by the Javis folks. (@wikunia will be unhappy if I muck this up again! https://github.com/Wikunia/Javis.jl/pull/149).

**Comment by Sov-trotter** [comment]
Will do that. Thanks

**Comment by cormullion** [comment]
Good stuff!

**Comment by Wikunia** [comment]
Haha @cormullion I'm always happy with you!
Does this change some Javis stuff now? As @Sov-trotter is working on Javis I suppose he'll notice though :smile:

**Comment by cormullion** [comment]
:) I worry that I might change something small and ruin your day... 😃

**Comment by Sov-trotter** [comment]
Thanks @cormullion . 
Could you tag a minor release?

**Pull request merged**
