### PR TITLE
Issues 250 exception

### PR DESCRIPTION
**Pull request by oheil**

### CODE REVIEW

**Comment by cormullion** [comment]
Thanks for this, I appreciate your efforts! 

I'll have a look at this over the holidays. I think this is calling `get_current_drawing_save()` rather a lot - four times every time we change the color? - but don't know what else to do yet.,,

Have a good holiday!

**Comment by oheil** [comment]
> I think this is calling `get_current_drawing_save()` rather a lot

OK, I check it and perhaps there is room for further improvement...

**Comment by oheil** [comment]
It's 5 times ! ;-)

**Comment by oheil** [comment]
I think it's more an issue with:
```
function setcolor(col::AbstractString)
    temp = parse(RGBA, col)
    # set Luxor settings
    set_current_redvalue(temp.r)
    set_current_greenvalue(temp.g)
    set_current_bluevalue(temp.b)
    set_current_alpha(temp.alpha)
    # and set Cairo context too
    Cairo.set_source_rgba(get_current_cr(), temp.r, temp.g, temp.b, temp.alpha)
    return (temp.r, temp.g, temp.b, temp.alpha)
end
```
This should be changed to something like:
```
function setcolor(col::AbstractString)
    temp = parse(RGBA, col)
    # set Luxor settings
    set_current_color(temp.r,temp.g,temp.b,temp.alpha)
    # and set Cairo context too
    Cairo.set_source_rgba(get_current_cr(), temp.r, temp.g, temp.b, temp.alpha)
    return (temp.r, temp.g, temp.b, temp.alpha)
end
```

**Comment by oheil** [comment]
What do you think about renaming all those not exported functions to _name, e.g.:
set_current_redvalue(r)  => _set_current_redvalue(r)

I have done it here already locally, just needs uploaded to branch.

**Comment by oheil** [comment]
Would be best in a separate PR, so you may check it here:
https://github.com/oheil/Luxor.jl/tree/pretty-and-optimize

**Pull request merged**
