### PR TITLE
Consistently use US spelling for center, allow UK centre as synonym

### PR DESCRIPTION
**Pull request by ScottPJones**

### CODE REVIEW

**Comment by cormullion** [comment]
Great stuff! This project really needs to be more consistent since it was started up with Julia v0.3 and has been cobbled together in spurts since then! 😀

**Comment by ScottPJones** [comment]
But, it's *so* fun!  Note: the unsuccessful checks are simply because of 1) a bug in codecov not correctly counting a code split on two lines as being covered 2) adding more lines total ends up making the percentage drop, even without any real drop in number of covered lines 3) needs some more tests to handle the synonyms I added (I'll push those shortly)

**Comment by ScottPJones** [comment]
@cormullion I think I may have found a bug: line 183 of curves.jl is:
```julia
    if startangle < startangle
```
which I think should be `if endangle < startangle`

**Comment by cormullion** [comment]
There's a few things like this in the code – perhaps similar to #13? When I'm back home next week I'll investigate! Glad to have someone with your skills helping me!

**Comment by ScottPJones** [comment]
It's a pleasure to help out on something cool like this ;-)
That does look like it's related to #13 to me also.
For the testing, I wonder if there is any way of automating it better: I don't know if it's possible to simply compare the output pdf files to ones that have been checked by a human? (not sure if there's any metadata, like date produced, directory names, user name, in the PDF file that would need to be ignored when comparing)

**Comment by cormullion** [comment]
I've always tested by looking at the output, not very good, I know, but the eye is quite good at picking up differences. And the tests are currently more about making sure that things still work that used to work, rather than testing every possible input value. (Cairo doesn't always like certain input values...)

Perhaps one day more output could be switched over to SVG or EPS, and so diff'ed more easily.

**Comment by cormullion** [comment]
Thanks Scott!

**Pull request merged**
