### PR TITLE
[WIP] get_fontsize

### PR DESCRIPTION
**Pull request by Wikunia**
This should work when Cairo releases a new version. So I need to update the Project.toml `compat` section then. 
Maybe @cormullion can give feedback already whether that makes sense.

It seems like this is only working for the "toy" API.

### CODE REVIEW

**Comment by cormullion** [comment]
Awesome stuff - will be useful I'm sure. Thanks!

**Comment by cormullion** [comment]
How about we do something like this:

```
function get_fontsize()
    if @isdefined get_font_matrix
        m = get_font_matrix(Luxor.get_current_cr())
        font_size = sign(m.yy)*sqrt(m.yx^2+m.yy^2)
    else
        font_size = 12 # probably a safe default?
    end 
     return font_size
 end
```

That way we don't have to tie ourselves to a specific version of Cairo.jl etc...

**Comment by Wikunia** [comment]
I think the default font size is 10. It feels weird to me to have this function when it doesn't give the correct result though.

**Comment by cormullion** [comment]
That's true... ¯\\\_(ツ)_/¯   I suppose it could error...or warn...? 

I'm just thinking to reduce package dependency churn, and avoid having to backport bug fixes to earlier versions of Luxor, etc... 

At the moment Luxor v2.3.0 works with all Julia 1 versions... If you tie it to the very latest Cairo version you'll have to edit eg https://github.com/JuliaGraphics/Luxor.jl/blob/master/.travis.yml ...  to remove versions 1.0 -> 1.2... And there will probably other version dependencies that will need adjusting...

**Comment by Wikunia** [comment]
Is it possible to move the if outside the function? I think it is. So only define the function in those cases. But I assume throwing an error works as well. Additionally show in the docstring that this only exits if the Cairo version is...
And when 1.6 becomes LTS you might want to just support from there.

**Comment by cormullion** [comment]
Did you decide what you wanted to do? I don't know if you can conditionally export functions, although you conditionally define them? And then change the compat ranges as well... Or you can just error... :)

**Comment by Wikunia** [comment]
I think throwing an error is fine with me. Will make that change later. Doing some more  Javis stuff now :wink:

**Comment by Wikunia** [comment]
I think the compat bounds are fine as they released it as v1.0.5 and not 1.1
I'm not sure how to test this properly though. Currently it tests if it throws an error when it should or whether it worked when v1.0.5 or later is installed. :smile:

**Comment by cormullion** [comment]
Cool, thanks. Will make a new release soon!

**Comment by Wikunia** [comment]
Sorry I screwed up the test. You don't import Cairo in the tests do you?

**Comment by cormullion** [comment]
No, only Cairo usage is `using Cairo` I think.

**Comment by cormullion** [comment]
No, wait, there's `import Cairo.CAIRO_PATH_MOVE_TO` in `test/get_path_flat.jl`...

**Comment by Wikunia** [comment]
Oh okay I went another route now which might be more what users would use.

**Comment by cormullion** [comment]
Thanks!

**Pull request merged**
