### PR TITLE
svg Drawing placeimage support (unfinished)

### PR DESCRIPTION
**Pull request by guo-yong-zhi**
See https://github.com/JuliaGraphics/Luxor.jl/issues/134
This is an incomplete support.
First, png Drawing is not supported.
Second, the svg alpha background is not handled properly.
That is:
```julia
using Luxor # master 
m1 = @svg  begin
    background(0,0,0,0)
    juliacircles(10) 
end 40 40

@draw begin
    for i in 1:50
        pos = rand(BoundingBox())
        @layer begin
            translate(pos)
            rotate(rand() * 2π)
            placeimage(m1, centered = rand(Bool))   # <-
        end
    end
end 100 100
```
->
图片

### CODE REVIEW

**Comment by cormullion** [comment]
Looks promising - let me know if/when you want to have this considered for merging...!

**Comment by cormullion** [comment]
I'm not sure this would work anyway:

```julia
m1 = @svg  begin
    background(0,0,0,0)
    juliacircles(10) 
end 40 40
```

I recommend using:

```julia
m1 = Drawing(40, 40, :svg)
origin()
juliacircles(10) 
finish()
```

for SVG with transparent backgrounds (but I think that this is just going over https://github.com/JuliaGraphics/Luxor.jl/issues/107 again).

**Comment by guo-yong-zhi** [comment]
Do we have some way to convert png and other bitmap typed `Drawing` to a `Matrix{ARGB32}`? If yes, maybe we can apply  `placeimage` to the result of `@png` directly. If no, you can merge and close it.

**Comment by guo-yong-zhi** [comment]
merge to https://github.com/JuliaGraphics/Luxor.jl/pull/138

**Pull request closed without merging**
