### PR TITLE
PCRE match limit exceeded

### PR DESCRIPTION
**Pull request by oheil**
resolved.

### CODE REVIEW

**Comment by cormullion** [comment]
Does all this regex stuff run on every SVG, large or small, or just a subset? 

For performance reasons, I’m starting to think we shouldn’t be doing all this processing here.

**Comment by oheil** [comment]
It runs on every SVG. If not, it's a bug. In general it is made defensive, so if something is different it does nothing, that's the idea. I don't think performance is a problem here as it returns early if no cairo background transform is found. It's slowest if the patch needs to be applied.

**Comment by cormullion** [comment]
You could make it so that any post-processing function runs if you ask it to - perhaps optionally pass a function in:

```
function  finish(; svgpostprocess=nothing)
  if svg ...
     if isafunction(postprocess)
         svgpostprocess(buffer)
     end
```

that way, any SVG postprocessing can be done if required, and none is done if not...

This might also have some other uses...

**Comment by oheil** [comment]
Yes, ok. But default should be to do the patch:
`function  finish(svgpostprocess=true)`
Don't you think?

**Comment by cormullion** [comment]
I think outputting Cairo's default SVGs should be the default, outputting specialyl post-processed ones should be opt-in. If it's a Cairo problem, then it's better fixed upstream?

**Comment by oheil** [comment]
Yes, it would be best if cairo would resolve it, but I don't think this will happen soon if ever.
I wonder, why we start this discussion again? Remember, this is just a regression bug of the last PR about the Svg issue 150 "Boundless recording surfaces do not currently work with svgs".

Doing this all now only if user explicitly wants it make it all questionable.

Anyways, looking at the RegExs, there seems to be room for optimizations. Somehow some things are in the wrong order...

I will update the PR now, adding an optional flag (default true) and adding a flag to disable the `class="luxor_adjusted"` marker.

**Comment by oheil** [comment]
Hmm.. ok. I will change it so that only if `finish`'ed is called from `snapshot` will do the patch. Better?

**Comment by hustf** [comment]
I hope that last compromise proposal from oheil goes through, as most users won´t read the documentation in advance. Sticking to mostly positive coordinates is, for me, not the default.

Keeping this package simple and close to Cairo is a huge advantage, and keeping maintenance cost of the code here low is of prime importance. But having code that is run as an exception, from my perspective, actually increases the risk of bugs. 

No matter what you conclude: Thank you very much; this Cairo-svg bug made me struggle for a very long time in private / work projects, because naturally I blamed my own understanding for a long time. And the errors were discovered when I was ready to put graphics in reports.

**Comment by oheil** [comment]
The latest version is now even more defensive.
The whole SVG :rec background cairo issue patch is now only applied, if we internally finish from a :rec snapshot to a :svg.
If the patch is applied, the default is to mark the result with class="luxor_adjusted". I think we need this as a default to know when people open new issues that it may be a result of this patch. In this case the marker should show up. Actually this is the only purpose of this.
It can be switched off with keyword parameter `addmarker=false`, e.g.
```
snapshot( ; fname="test.svg", cb=BoundingBox(Point(-150,-150), Point(150,150)), addmarker=false )
```
The user can force the patch with keyword parameter `svgpostprocess = true`, e.g.:
```
finish( ; svgpostprocess = true )
```
The patch is than applied if we write to svg and only if the transformations are found in the svg. Now the routine returns as early as possible whenever the patch will not be applikable to be as performant as possible.

**Comment by cormullion** [comment]
> I wonder, why we start this discussion again?

Yes, sorry - I sometimes click Merge too enthusiastically, I should really take more time to study what's inside and test it more thoroughly...

**Comment by oheil** [comment]
> > I wonder, why we start this discussion again?
> 
> Yes, sorry - I sometimes click Merge too enthusiastically, I should really take more time to study what's inside and test it more thoroughly...

No, actually you are doing quite well. All your objections have been very right and plausible. This is a workaround for another  librarys issue, so we should be maximal cautious. When this issue is resolved in cairo, this code will barely do anything in future, except for a single RegEx and a few if's (didn't count them now). The corresponding tests check for this and throw a warning. So we can check in future, if the patch can be removed from Luxor.

**Comment by cormullion** [comment]
Cool. Do we have enough tests for this stuff?

**Comment by oheil** [comment]
> Cool. Do we have enough tests for this stuff?

Obviously not ;-) But we have @hustf  ;-)

Should I create some more from @hustf testing and M(not)WE code snippets? This would involve creating huge SVGs during testing which may be not a good idea because of limited resources on the test VMs (or whatever they are).

**Comment by hustf** [comment]
Hi, sorry for not following up more closely. I met some unexpected behaviour when testing on Mac, but haven't tied it to an issue or had the chance to find out why. It's regarding current drawing() on thread no. 2, and the code there is hard to read. Most likely, my errors are just due to versioning/ tidying up. But I suggest waiting a bit with the next release

**Pull request merged**
