### PR TITLE
more placeimage interface

### PR DESCRIPTION
**Pull request by guo-yong-zhi**

### CODE REVIEW

**Comment by cormullion** [comment]
Perhaps we can improve the UI for this. We could have two unexported handler functions:

```
function _readsvgstring(str)
    r = Rsvg.handle_new_from_data(str)

    if r.ptr == C_NULL
        throw(error("_readsvgstring(): can't read SVG content from this string."))
    end

    d = Rsvg.handle_get_dimensions(r)
    if iszero(d.width) || iszero(d.height)
        throw(error("_readsvgstring(): can't get dimensions from this SVG image."))
    end
    return Luxor.SVGimage(r, d.em, d.ex, d.width, d.height)
end

function _readsvgfile(fname)
    if Base.stat(fname).size == 0
         throw(error("readsvg(): SVG file $fname not found"))
    end
    r = Rsvg.handle_new_from_file(fname)

    if r.ptr == C_NULL
        throw(error("readsvg(): couldn't read this SVG file"))
    end

    d = Rsvg.handle_get_dimensions(r)
    if iszero(d.width) || iszero(d.height)
        throw(error("readsvg(): can't get dimensions from this SVG image in $(pathname)."))
    end

    return Luxor.SVGimage(r, d.em, d.ex, d.width, d.height)
end
```

Then the top level exported function would be simply:

```
function readsvg(str) 
   # str is either pathname or pure SVG code
   # unfortunately is path fails if the string is longer than 255 characters
    if length(str) > 255 # don't check ispath, assume SVG string
        _readsvgstring(str)
    elseif ispath(str) # check is a file
        _readsvgfile(str)
    else
        _readsvgstring(str)
    end
end
```

which accepts a string, either a pathname or pure SVG.

**Comment by guo-yong-zhi** [comment]
is `ispath` expensive? how about directly check it. 
```julia
function readsvg(str) 
# str is either pathname or pure SVG code
    if ispath(str) # check is a file
        _readsvgfile(str)
    else
        _readsvgstring(str)
    end
end
```

**Comment by cormullion** [comment]
I tried that but it fails on long strings.  I think it’s probably just an OS call so should be inexpensive.

**Comment by cormullion** [comment]
A more elegant alternative would be to check the first n bytes of the string to see if it’s SVG. I don’t know what variations could be expected.

**Comment by guo-yong-zhi** [comment]
> 
> 
> I tried that but it fails on long strings. I think it’s probably just an OS call so should be inexpensive.

dose 'fails on' means the `ispath` function crashed? how to recurrence it.

**Comment by cormullion** [comment]
Just pass a string to ispath that’s longer than 255 chars (like most SVG code. I’m on Mac, it might vary by OS.

**Comment by guo-yong-zhi** [comment]
Well, it's ok on windows.
I think your solution is ok. Will you update it to the PR or let me do that?

**Comment by cormullion** [comment]
I’m very happy for you to do it if you want to - it’s your PR!😂 I don’t mind.

**Comment by cormullion** [comment]
Thanks for your great contributions!! The test failures are just because I haven't yet updated the appveyor to drop Julia < 1.3.... Waiting till 1.6 to release Luxor 2.8...

**Pull request merged**
