### PR TITLE
Move from @require to v1.9 Ext

### PR DESCRIPTION
**Pull request by hustf**
modified:   Project.toml
	modified:   appveyor.yml
	new file:   ext/LuxorExt.jl
	renamed:    src/latex.jl -> ext/latex.jl
	modified:   src/Luxor.jl

Ref. issue #275. Also, KristofferC [talking](https://youtu.be/TiIZlQhFzyk?t=738), and his [template](https://github.com/KristofferC/PGFPlotsX.jl) with a few extra bells:

### CODE REVIEW

**Comment by hustf** [comment]
We define three functions for export. The lecture demonstrates extending existing functions, and this approach didn't work. So one option is to define e.g.

```
latextextsize(x) = throw(ArgumentError("latextextsize can only be called with type LaTeXString from package `LatexStrings.jl`"))
```

The properly defined function returns a tuple of numbers, so not throwing an error would introduce type instability. (not that we care much about that). I'm leaving this for later, in case anybody has a comment already. In the meantime, feel free to take over at any time!

**Comment by cormullion** [comment]
Thanks! It looks more complicated than I thought at first... I'll try it out soon and see how it works.

**Comment by hustf** [comment]
I believe it will be hard to hit the extension code loading lines with test coverage. So I consider this finished. It should be completely non-breaking; no interface changes at all.

**Comment by cormullion** [comment]
According to this https://github.com/cjdoris/PackageExtensionCompat.jl - and  https://discourse.julialang.org/t/package-extensions-for-julia-1-9/93397/9 - it's 'easy' to use `requires` at the same time as package extensions, so it might be possible to easily obtain greater compatibility.🤔

**Comment by hustf** [comment]
It is possible, yes! And the template has a relevant example. I personally prefer to cut down on the complexity and not put effort into supporting old versions. To me, the point is simplicity, clearer compartmentalisation and improved compile times. If we put in the code for compatibility, the simplicity at least is reduced.

Testing on Julia 1.6 and 1.9 requires a little more energy and time per commit.

So I guess my personal freference is still to drop the compatibility effort, and rather wait (for example until Julia 2.0) before reaping the benefits of the new system and fully drop Julia pre 2.0. Or to simply drop Julia pre v1.9 now.

**Comment by cormullion** [comment]
Thanks for all your hard work! I think we should go for a 3.9 release with a increased Julia requirement of v1.9...

But I remember that this all started  with a suggested decoupling of FFMPEG... :) Is that easy to add to this PR?

**Comment by hustf** [comment]
I'm glad we think along the same lines!
 
I believe it would be benefical to separate FFMPEG in it's own PR. I don't feel confident to take longer steps, this being my first time and all. 

Installing FFMPEG as a requirement to running some function could be considered a breaking change. Old code (parts of it mine) would stop working until users installed and loaded FFMPEG in their environment.

I haven't modified the documentation either. This PR probably motivates no documentation changes, while the added step of loading FFMPEG at need would.

**Pull request merged**
