### PR TITLE
multi drawings complete (somehow)

### PR DESCRIPTION
**Pull request by oheil**

### CODE REVIEW

**Comment by guo-yong-zhi** [comment]
Is this PR related to https://github.com/JuliaGraphics/Luxor.jl/issues/117?

**Comment by oheil** [comment]
No. Using threads and checking issues with it is next on my agenda...
It is completing this https://github.com/JuliaGraphics/Luxor.jl/pull/236

**Comment by cormullion** [comment]
Perhaps some of these functions would be better named as `...index()` and `...indices()` since they return or set index values rather than drawing objects? 

One day we might have named drawings (an extra field in the struct perhaps?) rather than these old-school numbers... 🙂

**Comment by oheil** [comment]
Actually they were named ...index ;-) and I found ...drawing better. But no problem, I will change back to index.
And the named drawings I also thought already about, but thought, this is something for another time. One step per step :-)

**Comment by cormullion** [comment]
With multiple dispatch you could have `drawing_index()` for `get` and `drawing_index(n)` for `set`...  Anyway, It can be done how you like.

**Comment by oheil** [comment]
Yes, of course, as you wish.  There is not much like or dislike in me regarding those things.

**Comment by oheil** [comment]
1)
get_indices()
get_current_index()
set_current_index(i::Int)
get_next_index() 
set_next_index()

2)
drawing_indices()
drawing_index()
drawing_index(i::Int)
get_next_drawing_index()
set_next_drawing_index()

or something else?

**Comment by cormullion** [comment]
Probably 

```
drawing_indices()
get_drawing_index()
set_drawing_index()
get_next_drawing_index()
set_next_drawing_index()
```
are the most explicit, consistent, and predictable names. Longer but more self-explanatory...?

**Comment by oheil** [comment]
Yes, that's how it should be then 👍

**Comment by cormullion** [comment]
Thanks! Let's see how it works... :)

**Pull request merged**
