### PR TITLE
:zap: Added more unicode characters not supported by MathTeXEngine.

### PR DESCRIPTION
**Pull request by davibarreira**
Very small PR adding more unsupported unicodes to the list to make them available for LaTeX users.

### CODE REVIEW

**Comment by cormullion** [comment]
Cool, thanks!

At some point I want to find out what that function is doing with `setfont/settext` and get it working with text paths, like the other LaTex, but at the moment I don't want to know.... :)

**Comment by davibarreira** [comment]
What function exactly ? :X
I could tell you, whenever you want to know haha.

**Comment by cormullion** [comment]
Well, here you do both `fontface` and `setfont`, and  both `text` and `settext`, and wasn't quite sure why your were switching between toy and pro.



latex.jl: 193...
```julia
    fontface(text[1].font.family_name)
    fontsize(font_size * text[3])

    if string(text[1].char) == "⨟"
        setfont(text[1].font.family_name, font_size * text[3])
        Luxor.settext(string(text[1].char), Point(text[2]...) * font_size * (1, -1)+Point(0.25,0.3)*font_size)

    elseif text[1].represented_char == '{' || text[1].represented_char == '}'
        Luxor.text(string(text[1].char), Point(text[2]...) * font_size * (1, -1)+Point(0,-0.8)*font_size)

    elseif string(text[1].char) in extrachars
        setfont(text[1].font.family_name, 1.3font_size * text[3])
        Luxor.settext(string(text[1].char), Point(text[2]...) * font_size * (1, -1)+Point(0,0.3)*font_size)

    else
        Luxor.text(string(text[1].char), Point(text[2]...) * font_size * (1, -1))
```

Perhaps you can add some comments next time you're bored... :)

**Comment by davibarreira** [comment]
Hmm, I don't know exactly the difference between `fontface` and `setfont`, and `settext`and `text`.
When I use Luxor, I use the `fontface` and `text` functions. Yet, for some reason, these functions did not work when I wanted to write these extra unicodes. I tested using  `setfont`, and `settext`, and it worked. So I just went with it.

**Comment by davibarreira** [comment]
The first `fontface` could have been placed inside the last `else` and inside of  the second `elseif`, but I just used it on the top instead.

**Comment by cormullion** [comment]
Oh yes, that jogs my memory - the available font lists are different in toy and pro, I think. One day … 😀

**Pull request merged**
